# Introduction Numpy Arrays 
* Creating Arrays from Python Lists
* Creating Arrays from scratch

In [8]:
# import numpy(Numerical python lib)
import numpy as np

In [7]:
# Fixed type arrays in python
import array
L=list(range(10))
A=array.array('i',L)
type(A),type(L)

(array.array, list)

In [10]:
# creating array from python lists
# interger array (* Remember numpy array are constrained to that all contain the same type. If type do not match numpy 
# upcat it )

np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [12]:
# Here integer are upcast to float
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [16]:
# spefic data type while creating 
np.array([33,4,2,3], dtype='float32')

array([33.,  4.,  2.,  3.], dtype=float32)

In [30]:
# Multidemnional array using lists of list.
#Nested list result in multi dem array
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [31]:
# creating arrays from sacratch
#create length 10 integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
#create 3x5 float point array filled with 1s
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
#creating 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [36]:
# Creating array filled with a linear sequence
# starting at 0 ending at 20 stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# create array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
#create a 3x3 array filled with uniformly distributed random 0 and 1 
np.random.random((3,3))

array([[0.74743487, 0.95474785, 0.30776677],
       [0.99062119, 0.05153191, 0.82829212],
       [0.33321638, 0.00910302, 0.55298331]])

In [40]:
# create array of normally distributed random values with 0 mean and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 1.68145541, -0.41701556, -2.07970643],
       [ 1.30088652,  1.47299631, -0.01290634],
       [-0.28518986, -0.32772141, -1.50091472]])

In [42]:
# create a 3x3 array of random integers in th interval [0,10]
np.random.randint(0,10,(3,3))

array([[3, 4, 0],
       [2, 4, 3],
       [1, 5, 2]])

In [43]:
# create 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# create an unintialized array of three integers. The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])